name: "TEST"
description: "TESTDescription"
author: "hello"
inputs:
  GIT_TOKEN:
    description: GitHub token used to make API requests
    required: true
  pr_title:
    description: pr_title token used to send to Slack
    required: false
  WEBHOOK_URL:
    description: Webhookurl
    required: true
  GITHUB_CONTEXT:
    description: GITHUB_CONTEXT
    required: true
  OPEN_ISSUES_COUNT:
    description: OPEN_ISSUES_COUNT
    required: true
  GITHUB_PR_URL:
    description: GITHUB_PR_URL
    required: false
runs:
  using: "node16"
  main: "./index.js"