name: TestJavaScript

on:
  pull_request:

jobs:
  first-job:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
      
      - name: Run Test
        run: echo hello

      - name: Run jsfile
        uses: ./
        with:
          GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          pr_title: ${{ github.event.pull_request.title }}
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          GITHUB_CONTEXT: ${{ toJSON(github) }}
          GITHUB_PR_URL: ${{ github.event.pull_request.html_url }}
          OPEN_ISSUES_COUNT: ${{ github.event.pull_request.epository.open_issues_count}}
