name: TestJavaScript

on:
  pull_request:

jobs:
  first-job:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
      
      - name: Run Test
        run: echo hello

      - name: Run jsfile
        uses: ./
        with:
          GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          pr_title: ${{ github.event.pull_request.title }}
