name: TestJavaScript

on:
  push:

jobs:
  first-job:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
      
      - name: Run Test
        run: echo hello

      - name: Run jsfile
        uses: ./
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
